### ISSUE TITLE
Add the ability to transcribe audio URLs (ex. presigned AWS URL)

### ISSUE THREAD

**Issue by aleksandr-smechov** [Wordcab/wordcab-transcribe#11]
Add an endpoint for transcribing audio URLs (ex. presigned AWS or GCP URL)

**Comment by chainyo** [comment]
pre-signed URLs are simple URLs but sometimes require tokens in the headers.

I implemented something similar in the `wordcab-python` package.

https://github.com/Wordcab/wordcab-python/blob/522af3cd6cd3f8e8c50a7bb68abef155f00f2b59/src/wordcab/core_objects/source.py#L133-138

I could take on this.

**Comment by aleksandr-smechov** [comment]
I have an async implementation ready using aiohtto, will ask you to review when I push the branch
