### ISSUE TITLE
Long files tend to error out

### ISSUE THREAD

**Issue by aleksandr-smechov** [Wordcab/wordcab-transcribe#116]
Audio/video files over an hour sometimes error out. Probably due to diarization.

**Comment by chainyo** [comment]
I can't reproduce the error.

Tried with this youtube video: https://youtu.be/RcYjXbSJBN8

I will try with a local audio file.

**Comment by aleksandr-smechov** [comment]
For reference this was a 1.5+ hour video in a non-English language

**Comment by chainyo** [comment]
Fixed by the recent updates in the diarization process and release `v0.4.0` #186
