### ISSUE TITLE
Support translation into languages other than English

### ISSUE THREAD

**Issue by aleksandr-smechov** [Wordcab/wordcab-transcribe#117]
Support translation into languages [other than English](https://github.com/guillaumekln/faster-whisper/issues/245).

**Comment by chainyo** [comment]
Do we want to add translation as a sub-module? Because, from the Issue you linked, it seems that Whisper can only translate to English.

**Comment by aleksandr-smechov** [comment]
I'd set this as stale for now as it's totally separate
