### ISSUE TITLE
Error in diarization: CUDA out of memory

### ISSUE THREAD

**Issue by callmephilip** [Wordcab/wordcab-transcribe#129]
Running on `Quadro RTX5000`

Full error message below:

```Error in diarization: CUDA out of memory. Tried to allocate 1.60 GiB (GPU 0; 15.75 GiB total capacity; 8.37 GiB already allocated; 1.46 GiB free; 9.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Traceback (most recent call last): 

File \"/app/wordcab_transcribe/services/asr_service.py\", line 294, in runner
    results = await asyncio.get_event_loop().run_in_executor(
  File \"/usr/lib/python3.8/concurrent/futures/thread.py\", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
 File \"/app/wordcab_transcribe/logging.py\", line 89, in sync_wrapper
    result = func(*args, **kwargs)
  File \"/app/wordcab_transcribe/services/asr_service.py\", line 345, in process_diarization
    utterances = self.services[\"diarization\"](task[\"input\"])
  File \"/app/wordcab_transcribe/logging.py\", line 89, in sync_wrapper
    result = func(*args, **kwargs)
  File \"/app/wordcab_transcribe/services/diarize_service.py\", line 73, in __call__
    self.model.diarize()
  File \"/opt/pysetup/.venv/lib/python3.8/site-packages/torch/utils/_contextlib.py\", line 115, in decorate_context
    return func(*args, **kwargs)
  File \"/opt/pysetup/.venv/lib/python3.8/site-packages/nemo/collections/asr/models/msdd_models.py\", line 1180, in diarize
    self.clustering_embedding.prepare_cluster_embs_infer()
 File \"/opt/pysetup/.venv/lib/python3.8/site-packages/nemo/collections/asr/models/msdd_models.py\", line 699, in prepare_cluster_embs_infer
    self.emb_sess_test_dict, self.emb_seq_test, self.clus_test_label_dict, _ = self.run_clustering_diarizer(
  File \"/opt/pysetup/.venv/lib/python3.8/site-packages/nemo/collections/asr/models/msdd_models.py\", line 866, in run_clustering_diarizer
    scores = self.clus_diar_model.diarize(batch_size=self.cfg_diar_infer.batch_size)
  File \"/opt/pysetup/.venv/lib/python3.8/site-packages/nemo/collections/asr/models/clustering_diarizer.py\", line 456, in diarize
    all_reference, all_hypothesis = perform_clustering(
  File \"/opt/pysetup/.venv/lib/python3.8/site-packages/nemo/collections/asr/parts/utils/speaker_utils.py\", line 486, in perform_clustering
    cluster_labels = speaker_clustering.forward_infer(
  File \"/opt/pysetup/.venv/lib/python3.8/site-packages/nemo/collections/asr/parts/utils/offline_clustering.py\", line 1288, in forward_infer
    mat = getMultiScaleCosAffinityMatrix(
  File \"/opt/pysetup/.venv/lib/python3.8/site-packages/nemo/collections/asr/parts/utils/offline_clustering.py\", line 525, in getMultiScaleCosAffinityMatrix
    score_mat_torch = getCosAffinityMatrix(emb_t)
  File \"/opt/pysetup/.venv/lib/python3.8/site-packages/nemo/collections/asr/parts/utils/offline_clustering.py\", line 439, in getCosAffinityMatrix
    sim_d = ScalerMinMax(sim_d)
  File \"/opt/pysetup/.venv/lib/python3.8/site-packages/nemo/collections/asr/parts/utils/offline_clustering.py\", line 78, in ScalerMinMax
    v_norm = (X - v_min) / (v_max - v_min)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.60 GiB (GPU 0; 15.75 GiB total capacity; 8.37 GiB already allocated; 1.46 GiB free; 9.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

I am not sure how much of this is related to this library as opposed to some general CUDA jazz. Have you guys come across this before?

**Comment by chainyo** [comment]
HI @callmephilip, could you try to lower the batch size (line 11) for diarization in the config file `config/nemo/diar_infer_telephonic.yaml`.

Also what is the audio duration you are trying to transcribe?

**Comment by callmephilip** [comment]
trying to rebuild with new config and i am getting an error related to the base image `nvidia/cuda:11.7.0-cudnn8-runtime-ubuntu20.04`:

`=> ERROR [internal] load metadata for docker.io/nvidia/cuda:11.7.0-cudnn8-runtime-ubuntu20.04`

Quick [check on Docker Hub](https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=11.7.0) shows that the image is not there effectively. Did it get deprecated or something?

**Comment by callmephilip** [comment]
nvm, just saw [this](https://github.com/Wordcab/wordcab-transcribe/commit/b691afe2f06559af4eff24decf8209444b6a37b8) 😃 #livingonthedge

**Comment by callmephilip** [comment]
- i am now running on the latest `main`
- adjusted batch size to 64 (down from 128)
- i am now getting the following error: `{"detail":"Process failed, please check if the audio file is valid."}`

wondering if [this](https://github.com/Wordcab/wordcab-transcribe/commit/e7df3558391e47d5df9bf35c0a8affe24179480c) is now preventing more error context from propagating 

Docker container logs:

```
2023-07-01 12:03:04.937 | DEBUG    | wordcab_transcribe.logging:sync_wrapper:92 - process_transcription executed in 435.8863 secs
2023-07-01 12:03:04.937 | DEBUG    | wordcab_transcribe.logging:async_wrapper:106 - process_input executed in 437.0178 secs
2023-07-01 12:03:04.947 | DEBUG    | wordcab_transcribe.logging:dispatch:65 - Response status: 500, Process Time: 544.8351 secs
INFO:     161.230.164.189:38571 - "POST /api/v1/audio HTTP/1.1" 500 Internal Server Error
```

Regarding audio, it's `1.5 hours long`. Somehow, I was able to successfully process similar length audios before but now it's failing for certain files.

**Comment by chainyo** [comment]
> wondering if [this](https://github.com/Wordcab/wordcab-transcribe/commit/e7df3558391e47d5df9bf35c0a8affe24179480c) is now preventing more error context from propagating

Good catch this was a bad exception catch. I will update this asap.

**Comment by chainyo** [comment]
The exception returns have been fixed in the last PR #114.
The error messages should be better now.

Feel free to re-open this if you are still facing issues.

**Comment by callmephilip** [comment]
@chainyo still seeing this error intermittently on some pieces of content. i've noticed that you do call CUDA clean up routine [here](https://github.com/Wordcab/wordcab-transcribe/blob/33979b3955a0c872fa5a070688053aac726d34e5/wordcab_transcribe/services/align_service.py#L180) in the alignment service. however this call is missing in other services. would it make sense to include clean up in other services as well?

**Comment by callmephilip** [comment]
specifically, maybe inside transcription service [here](https://github.com/Wordcab/wordcab-transcribe/blob/main/wordcab_transcribe/services/transcribe_service.py#L337)

**Comment by callmephilip** [comment]
nvm, just tried this and it seems like it has no effect. still getting CUDA out of memory error

**Comment by chainyo** [comment]
You are running on a 16GB VRAM GPU right?

What's the language and the input source you are trying to transcribe?
Also could you provide the parameters you are using (like diarization, alignment...)

**Comment by callmephilip** [comment]
> You are running on a 16GB VRAM GPU right?

Yup. `Quadro RTX5000`

> What's the language and the input source you are trying to transcribe?

It's in English. I am using an mp3 version of [this video](https://www.youtube.com/watch?v=SVwLEocqK0E)

> Also could you provide the parameters you are using (like diarization, alignment...)

```
'alignment=true',
'diarization=true', 
'dual_channel=false',
'source_lang=en', 
'timestamps=s',
'word_timestamps=true',
```

**Comment by chainyo** [comment]
Great, thanks for sharing the parameters.

Could you try making `alignment=False`? The alignment process fails when the audio is more than 1 hour long.
With the recent changes and `faster-whisper` improvements, timestamps are even more precise, and alignment can be useless at some point unless you need crazy precision (that alignment cannot provide anyways).

**Comment by callmephilip** [comment]
it's still failing even with alignment turned off

**Comment by aleksandr-smechov** [comment]
@chainyo The process started off at around 30% VRAM utilization, reached nearly 90-100% VRAM during diarization, then settled to 40-45% (likely during alignment, since I had that on). This was on an A10G (24GB VRAM). So my guess is NeMo's inefficient use of the GPU (we should open a new issue on this if it hasn't been already).

![image](https://github.com/Wordcab/wordcab-transcribe/assets/35517862/682618bc-59bb-48f2-abc7-9eb6e8975518)

@callmephilip The interim solution would be splitting the file in half, while we tinker with NeMo. Not ideal, but anything under an hour should work.

**Comment by chainyo** [comment]
It looks like one step inside the complete NeMo process requires VRAM proportionally to the audio duration. This is not the case for previous steps where audio is cut in chunks to avoid CUDA problems, as logged by NeMo.

**Comment by aleksandr-smechov** [comment]
Hi @tango4j, since you worked on NeMo's diarizer, wonder if you have any thoughts/ideas about the spike in VRAM usage for longer audio files?

**Comment by chainyo** [comment]
The problem has been isolated and understood with PR #180.

I will work on a fix to allow larger audio files in the `Clustering` step of the diarization process.

**Comment by chainyo** [comment]
Hi, @callmephilip. PR #186 fixes your CUDA OOM error on the youtube video you linked. We added a dynamic multiscale diarization strategy that could reduce the diarization precision a bit but allow the full inference on GPU with restricted VRAM (16GB and less).
