### ISSUE TITLE
Contributing cannot be done with current instructions

### ISSUE THREAD

**Issue by jissagn** [Wordcab/wordcab-transcribe#130]
- [x] ~`nox` and `nox-poetry` are missing from deps~ add instructions to ensure `nox`, `nox-poetry` and `poetry` are installed beforehands
- [x] repo name is not right in README
- [ ] ~`test_config` fails on first try as the `.env` file is not loaded, so `USERNAME` is not correctly set~

**Comment by jissagn** [comment]
This PR https://github.com/Wordcab/wordcab-transcribe/pull/131 fixes the two first items, but I could'n find a way to properly load the `.env` file before running tests, therefore tests fail (specifically, the `USERNAME` check on `test_config.py` fails).

Any hint/idea ?

**Comment by chainyo** [comment]
@jissagn Do you have the `.env` in your project? So the `python-dotenv` should see and load it. Verify you are in the root folder of the project before running `nox` or any tests.

**Comment by jissagn** [comment]
I just found out that the `.env` is actually correctly loaded because the first settings tests pass : 

``` python
    def test_config() -> None:
        """Test default config settings with the .env file."""
        assert settings.project_name == "Wordcab Transcribe"
        assert settings.version == "0.3.1"

        # [...lots of settings tests going on...]

        assert settings.youtube_endpoint is True
        assert settings.live_endpoint is False
    
>       assert settings.username == "admin"  # noqa: S105
E       AssertionError: assert 'jissagn' == 'admin'
E         - admin
E         + jissagn

```
but somehow the `username` env is overriden by my system's username (the one you get with shell command `whoami`).
I use Ubuntu on zsh.

**Comment by chainyo** [comment]
> but somehow the `username` env is overriden by my system's username (the one you get with shell command `whoami`). I use Ubuntu on zsh.

It's super weird, because I never used the project with an `admin` name, and I have always something like `chainyo` as my OS username. Did you modify the `.env` by any chance?

**Comment by jissagn** [comment]
No I did not change the file. Well I'll try with a fresh clone/install and update with my results here.

**Comment by chainyo** [comment]
> So my guess is that `USERNAME` is a system variable that cannot be easily overriden (at least on Ubuntu). Which OS are you using @chainyo ?

I'm using MacOS, Ubuntu, and Linux VMs on GCP, I never faced this problem before.

Thanks for investigating. I would consider updating the variable's name to be more specific.
