### ISSUE TITLE
Discrepancies between text and words data

### ISSUE THREAD

**Issue by callmephilip** [Wordcab/wordcab-transcribe#134]
I am seeing strange looking discrepancies between `text` and `words` attributes. Here's an example:

```
{
      "text": "He is awesome. What's up, dude? We're live. What's going on? What up?",
      "start": 26.82,
      "end": 39.14,
      "speaker": 1,
      "words": [
        { "word": "He", "start": 26.82, "end": 27.01, "score": 0.95 },
        { "word": "is", "start": 27.07, "end": 27.19, "score": 0.8 },
        { "word": "awesome.", "start": 27.41, "end": 27.66, "score": 0.19 },
        { "word": "We're", "start": 37.48, "end": 37.64, "score": 0.8 },
        { "word": "live.", "start": 37.68, "end": 37.9, "score": 0.66 },
        { "word": "What's", "start": 37.96, "end": 38.08, "score": 0.3 },
        { "word": "going", "start": 38.1, "end": 38.33, "score": 0.67 },
        { "word": "on?", "start": 38.42, "end": 38.48, "score": 0.96 },
        { "word": "What", "start": 38.9, "end": 39.01, "score": 0.14 },
        { "word": "up?", "start": 39.09, "end": 39.14, "score": 0.26 }
      ]
    }
```

Notice how `What's up, dude?` is missing inside words section

**Comment by chainyo** [comment]
Thanks for reporting @callmephilip 
Are you using a youtube video, or do you have a sample I could try to reproduce on my side to see where this bug comes from?

**Comment by callmephilip** [comment]
I am using an mp3 version of [this video](https://www.youtube.com/watch?v=uRt8ZlY-7uw). this is reproducible directly as well via `/api/v1/youtube`

**Comment by chainyo** [comment]
Hi @callmephilip, I did some investigation. Thanks for helping me by posting the youtube video as a test.

So actually, the `What's up dude` is hallucinated in the grouped text, which is why it's not in the content of the words. 
By the way, with the actual `main` branch, I don't find the hallucinated part. Could you update your local version and give it a go again?

**Comment by chainyo** [comment]
Hi, @callmephilip we just merged a new version of the API (not as a release yet). You should experiment with better accuracy in transcription/diarization. Let me know how it goes with the last update.

**Comment by chainyo** [comment]
I'm closing it right now, feel free to re-open if you still face an error @callmephilip.
