### ISSUE TITLE
Move from poetry to hatch

### ISSUE THREAD

**Issue by chainyo** [Wordcab/wordcab-transcribe#217]
The current testing and build implementation featuring `poetry` and `nox` is cumbersome/burdensome. Not so great overall...

Hatch could give us a faster path for dev and easy project installation. It could also lead to smaller containers.

**Comment by aleksandr-smechov** [comment]
@chainyo Any other upsides of switching to Hatch?

**Comment by chainyo** [comment]
@aleksandr-smechov 
* Smaller container
* Faster ci/cd pipelines
* Easier to create a package
* Easier to create a CLI

In fact, the single fact it goes through `pip` for the installation (instead of `poetry`) makes it great for many points.
