### ISSUE TITLE
Add utils function to run an api call for each endpoint

### ISSUE THREAD

**Issue by chainyo** [Wordcab/wordcab-transcribe#23]
We should have functions that automate API calls to the 3 different endpoints to make it easy and fast to use the API.

- [ ] YouTube video
- [ ] Local audio file
- [ ] Signed URL audio

**Comment by aleksandr-smechov** [comment]
@chainyo can you expand a bit on this

**Comment by chainyo** [comment]
> @chainyo can you expand a bit on this

@aleksandr-smechov simple functions that encapsulate in one line the API request process to avoid dealing with query/body params

**Comment by chainyo** [comment]
Fixed by #94
