### ISSUE TITLE
Upgrade faster-whisper to 0.8.0

### ISSUE THREAD

**Issue by aleksandr-smechov** [Wordcab/wordcab-transcribe#242]
Upgrade faster-whisper to 0.8.0

**Comment by chainyo** [comment]
The forked repository has been synchronized with the latest release of `faster-whisper`.

For next sync:
- Git clone the forked repository locally
- `git checkout master` (just to be sure to be on the master branch)
- `git fetch upstream` (Get the upstream repo =original faster-whisper updates)
- `git merge upstream/master`
- Resolve conflicts if there are some conflicts.
- `git push origin master`

**Comment by chainyo** [comment]
I'm re-opening this because the `_MODELS` object has changed from a tuple to a dict so I need to update the config file from `wordcab-transcribe`.
