### ISSUE TITLE
Check new batching from faster-whisper

### ISSUE THREAD

**Issue by chainyo** [Wordcab/wordcab-transcribe#252]
This feature would be helpful only on large GPUs with the diarization model on a separate GPU.

Currently, transcribing an audio file takes approximately 6GB of VRAM, and the rest of the GPU is used by the diarization model. If we batch files for transcription, we might face VRAM issues.

Should we enable batch transcription only on a multi-GPU setup? Wdyt? @aleksandr-smechov

**Comment by aleksandr-smechov** [comment]
Let's assume diarization is not an issue for VRAM (ex. it's run on a separate GPU) and go from there @chainyo. We'll see how this goes with one GPU first.
