### ISSUE TITLE
Examples of how to download the whisper models?

### ISSUE THREAD

**Issue by lox** [Wordcab/wordcab-transcribe#288]
It would be great to include some examples of how to download the whisper models in the correct folder structure!

**Comment by info-wordcab** [comment]
I'll add an issue to address this in the Readme, thank you!

**Comment by chainyo** [comment]
Before it appears in the README, it is detailed here: https://github.com/Wordcab/wordcab-transcribe/blob/fa83363e984174d36c87a472d04d243509b6a0ca/.env#L21-34

**Comment by aleksandr-smechov** [comment]
@lox Included in the example `.env` file and `README`.

**Comment by lox** [comment]
Apologies if I am being dense, but I can't see either the .env change or the README change! 

The way I am downloading the models now is:

```
pip install -U openai-whisper
```

and then running in a `python` repl:

```
import whisper
model = whisper.load_model("large-v3", download_root="~/whisper")
```

```
