### ISSUE TITLE
Build image

### ISSUE THREAD

**Issue by standyyyy** [Wordcab/wordcab-transcribe#29]
![Uploading Snipaste_2023-04-21_17-56-43.png…]()
Hello, thank you for your work. I spent some time successfully constructing the mirror image, but I found that it was very big, with 18G, so I wonder if I made a mistake in any step.

**Comment by standyyyy** [comment]
I made an error in the process of starting the mirror, and I can't start it for now. Any help is welcome, thank you
`
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.
`

**Comment by chainyo** [comment]
Hi @standyyyy, thanks for trying the project.

18GB is precisely what I get on my end. The image could be optimized, and we will look into it soon.

I'm not sure to understand how you got the error mentioned above. Could you explain more about what you did and what you are trying to do? Also, could you provide some details about your hardware?

**Comment by standyyyy** [comment]
hi, thank you for replying so quickly

The following is my system
System: windows10 Professional
cuda: 12.1
After constructing the image, I use the following command to start docker
`
docker run -d --name wordcab-transcribe --gpus all --shm-size 1g --restart unless-stopped -p 5001:5001 wordcab-transcribe:latest
`
After trying to reduce some parameters, I still cannot start. I am not sure why
If you can give me some advice, thank you very much
If you want to know more, please let me know
Thank you again

**Comment by chainyo** [comment]
It seems that your CUDA installation is not detected. It could come from the fact you are running on Windows.

Could you prepend any path to your cuda/cublas drivers before launching the docker container?

**Comment by standyyyy** [comment]
Hi @chainyo ,I'm glad you informed me after iterating. I tried many ways to solve this problem at the time, but it seemed that it was because of my own windows version. Since my windows version is 20H1, when I was looking for a solution, I saw that the Windows system version of 20H1 does not support docker-driven GPU, so I tried to upgrade my system version, but unfortunately, I failed. I will try again in the near future, because I need docker to drive GPU, try to convert other ONNX models into Tensorrt models for reasoning

**Comment by chainyo** [comment]
Great, so I'm closing this right now. Feel free to re-open it if you are still facing issues!

Thanks for sharing your experiences with Windows and Docker. Thanks to your comment, I'm not a Windows user so I could help Windows users best next time.

**Comment by standyyyy** [comment]
@chainyo 
Hello, after reinstalling the system and using the windows 22H2 version, I successfully used docker to run this project. I tested it yesterday. Except for the time being a little slow, everything else is great.
By the way, I found that when I use two-channel audio for recognition, some audio separation will fail, but I took out the separation code and ran it smoothly. I haven't had time to study the code carefully, and I haven't found it yet. what is the problem.
This is a great project.
I have also tried some speaker diarization solutions before, but after testing, I think NVIDIA NeMo's speaker diarization effect is better than pyannote-audio's speaker diarization. I am going to try to use the features of the voiceprint model to cluster and see how it works.

**Comment by chainyo** [comment]
Hi @standyyyy, thanks for your kind words.

Could you elaborate on the audio separation you have found?
Have you tried the latest batch process? On our end, it speeds transcription by 2x!

**Comment by standyyyy** [comment]
@chainyo 
I can't tell whether I'm using the latest version (because it's too close to the last update time) and I just pulled the code in the last two days. I'm not sure if I just downloaded the latest version. Let me provide it Pull down the properties of the folder and the size of the built container, can you help judge whether it is the latest version based on these? Maybe there is another easier way to judge whether it is the latest?
![image](https://github.com/Wordcab/wordcab-transcribe/assets/39285732/f3b1cf5a-ef2f-475f-8f8a-cf4950c362a2)
![image](https://github.com/Wordcab/wordcab-transcribe/assets/39285732/c24fc953-a232-42b5-abd2-0929f178a168)

**Comment by standyyyy** [comment]
![image](https://github.com/Wordcab/wordcab-transcribe/assets/39285732/01f1b211-7de3-46e6-8c74-955500685ed9)
I checked, the version is not the latest, is there a way to update to the latest without rebuilding the container?
Sorry, I forgot to reply to your question earlier. I checked the audio that I failed to separate. It was about 24 minutes long. Some of the audio failed to be separated. I tried to separate it again, but some parts still didn’t work.
When I discovered this situation, I found this part of the code that reported the error.
`
if result[0] != 0:
        raise Exception(f"Error splitting dual channel file: {filepath}. {result[2]}")
`
After looking at this code, I found that it is the code used to separate the left and right channels, and then I started to troubleshoot the problem. I thought it was my audio problem, so I extracted the split_dual_channel_file function and async_run_subprocess function separately for failure The audio used and found to be working fine.

**Comment by chainyo** [comment]
You can git pull the latest changes, and if you don't remove the docker image, the build process should use the old one as the base and only replace code files that need to be updated for `0.3.1` (I don't think there are changes in the used libraries, but I might be wrong).

Use `dual_channel` only if you have audio with a speaker on the right and another one on the left channels. Otherwise, it's not useful. Also, could you be sure to use a stereo file with these 2 channels? 

I have added a fallback #87 to avoid failed jobs if `dual_channel` is chosen with a valid stereo file.
