### ISSUE TITLE
Failed when building docker image: libgnutls30

### ISSUE THREAD

**Issue by yf-chau** [Wordcab/wordcab-transcribe#302]
When building a docker image using the provided Dockerfile it failed to find the package `libgnutls30=3.7.3-4ubuntu1.4`.

It might be a typo as it works when I changed the version number to `libgnutls30=3.7.3-4ubuntu1.5`, which is the version used in jammy-updates.
https://packages.ubuntu.com/jammy-updates/libgnutls30

**Comment by aleksandr-smechov** [comment]
Good catch @yf-chau, and yes it's a typo.
