### ISSUE TITLE
The the seconds decimal in the hms output should have a dot "." separator not a comma ","

### ISSUE THREAD

**Issue by aleksandr-smechov** [Wordcab/wordcab-transcribe#4]
For example:

`00:00:26,519` should be `00:00:26.519`

**Comment by chainyo** [comment]
I see from where does it come: https://github.com/Wordcab/wordcab-transcribe/blob/b2f7ae7551311fb2c8e50f3a342679c6e5629e5b/wordcab_transcribe/utils.py#L57

I will fix that.
