### ISSUE TITLE
Improve endpoints testing

### ISSUE THREAD

**Issue by chainyo** [Wordcab/wordcab-transcribe#47]
- [ ] Audio file
- [ ] Audio url
- [ ] Youtube
- [ ] Root

**Comment by aleksandr-smechov** [comment]
@chainyo Ok to close?

**Comment by chainyo** [comment]
@aleksandr-smechov Testing is still rudimentary here.

**Comment by chainyo** [comment]
I plan to add a lot of unit tests in the following days to reinforce the quality of the package.
