### ISSUE TITLE
Investigate on a better GPU usage

### ISSUE THREAD

**Issue by chainyo** [Wordcab/wordcab-transcribe#6]
Check if it's possible to accelerate request batching on GPU with `faster-whisper` current implementation.

Some reads:
* https://github.com/guillaumekln/faster-whisper/issues/100
* https://github.com/guillaumekln/faster-whisper/issues/66
* https://github.com/guillaumekln/faster-whisper/issues/59

**Comment by chainyo** [comment]
This is a bit stale for the moment. But I will check how to implement it into `faster-whisper` lib soon.

**Comment by aleksandr-smechov** [comment]
Nice, WhisperX has an interesting approach to refinement but just needs to be adapted for faster-whisper

**Comment by aleksandr-smechov** [comment]
Might be useful to consider: https://opennmt.net/CTranslate2/parallel.html?highlight=async
