### ISSUE TITLE
Create benchmarks

### ISSUE THREAD

**Issue by chainyo** [Wordcab/wordcab-transcribe#74]
To stay consistent and validate that new API/project updates are improving the entire process:

* Define youtube videos/audio files as reference
* Create benchmarks to assert a change not worse than before
* Create comparison benchmarks with:
    * original faster-whisper
    * openai/whisper
    * whisperX
    * our API
    * commercial ASR (AssemblyAI, Deepgram, etc)

**Comment by aleksandr-smechov** [comment]
Let's add the commercial ASRs as well

**Comment by aleksandr-smechov** [comment]
Being done with Rate That ASR (RTASR) https://github.com/Wordcab/rtasr
